export enum Category {
	CATEGORY_DEFAULT = 'default',
	CATEGORY_BROWSABLE = 'browsable',
	CATEGORY_TAB = 'tab',
	CATEGORY_ALTERNATIVE = 'alternative',
	CATEGORY_SELECTED_ALTERNATIVE = 'selected_alternative',
	CATEGORY_LAUNCHER = 'launcher',
	CATEGORY_INFO = 'info',
	CATEGORY_HOME = 'home',
	CATEGORY_PREFERENCE = 'preference',
	CATEGORY_TEST = 'test',
	CATEGORY_CAR_DOCK = 'car_dock',
	CATEGORY_DESK_DOCK = 'desk_dock',
	CATEGORY_LE_DESK_DOCK = 'le_desk_dock',
	CATEGORY_HE_DESK_DOCK = 'he_desk_dock',
	CATEGORY_CAR_MODE = 'car_mode',
	CATEGORY_APP_MARKET = 'app_market',
	CATEGORY_VR_HOME = 'vr_home',
	CATEGORY_CONTAINER_LOG = 'container_log',
	CATEGORY_VIDEO = 'video',
	CATEGORY_AUDIO = 'audio'
}
